version: '3.9'
services:
  edcb-wine:
    image: edcb-wine
    container_name: EDCB-Wine
    build:
      context: .
    restart: always
    ports:
      - "4510:4510/tcp" # EDCB TCP API
      - "5510:5510/tcp" # EpgTimerSrv.exe HTTP Server
      - "6510:6510" # VNC for Browser
      - "6511:6511" # VNC for VNC Viewer
    # Xfce のデスクトップ環境はなぜか特権モードでないと正常に動作しない
    privileged: true
    # ボリュームのマウント設定
    # /mnt/ はコンテナ内の EDCB からホストマシンに接続されている HDD にアクセスするために必要
    # 別途 HDD を /mnt/ 以下に適切な権限でマウントしておく必要がある (トラブル回避のため 777 (drwxrwxrwx) に設定することを推奨)
    volumes:
      - type: bind
        source: './EDCB/'
        target: '/EDCB/'
      - type: bind
        source: '/mnt/'
        target: '/mnt/'
